#!/usr/bin/env python3
"""Add the per-video stats branch to the live "Daily Analytics Digest" workflow.

The digest workflow (ENbQm9ctfNRcnOuT) is live-only — it is NOT generated by
n8n/generate.py. This script adds a second branch off its existing schedule
trigger that fans per-video rows into one Google Sheets tab per channel:

    Daily 06:00 Trigger ─┬─► Fetch Daily Analytics ─► ... (existing digest)
                         └─► Get video stats ─► Split video rows ─► Append video stats
                                   └─(error)─► Format error (reuses existing alert)

It patches via the n8n public REST API (GET → edit → PUT → activate) so existing
node expressions are preserved byte-for-byte — we deliberately avoid the n8n-mcp
SDK-reconstruction path, which has corrupted expressions before. The script is
idempotent (skips if "Get video stats" already exists) and refuses to PUT if it
would change any pre-existing node.

The new Google Sheets node clones the existing "Append to Analytics Sheet"
credential + document, writes to the tab named after each row's `channel`
(`sheetName` = {{ $json.channel }}), and maps the 16 data columns explicitly so
`channel` itself is NOT written as a column (the tab name identifies the channel).

PREREQUISITE: the four channel tabs (wordstrata, the-mythscape, open-verdicts,
bright-beasts) must already exist in the spreadsheet — googleSheets v4.7 `append`
does not create a missing tab.

GOTCHA: on the FIRST append to an *empty* tab, n8n builds the header row from the
incoming item's fields, which include the `channel` routing key — so an empty tab
gains a stray `channel` column. The append only ever *maps* the 16 data columns
(below), so it never fills `channel` after that; give each tab a fixed 16-column
header row (or delete the stray column once) and it won't reappear.

Run:
  N8N_API_KEY=<key> python scripts/add_video_stats_branch.py --dry-run
  N8N_API_KEY=<key> python scripts/add_video_stats_branch.py
(N8N_API_TOKEN is also accepted.)
"""

from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request

BASE_URL = os.environ.get("N8N_BASE_URL", "http://100.66.55.82:5678").rstrip("/")
API_KEY = os.environ.get("N8N_API_KEY") or os.environ.get("N8N_API_TOKEN", "")
DRY_RUN = "--dry-run" in sys.argv

WORKFLOW_ID = "ENbQm9ctfNRcnOuT"
TRIGGER_NODE = "Daily 06:00 Trigger"
SHEETS_NODE = "Append to Analytics Sheet"   # existing node we clone cred+doc from
ERROR_NODE = "Format error"                  # existing error formatter we reuse
FETCH_URL = "http://host.docker.internal:7860/analytics/videos"

# The 16 per-video columns (VideoStatRow), in tab order. `channel` is the tab
# selector only and is deliberately excluded from the written columns.
COLUMNS = [
    "date", "video_id", "url", "title", "published_at", "days_live",
    "views_total", "views_today", "likes_total", "likes_today",
    "comments_total", "comments_today", "watch_min_total", "watch_min_today",
    "shares_total", "shares_today",
]

SPLIT_JS = (
    "const report = $input.first().json;\n"
    "const out = [];\n"
    "for (const ch of (report.channels || [])) {\n"
    "  for (const row of (ch.rows || [])) {\n"
    "    out.push({ json: { ...row, channel: ch.channel } });\n"
    "  }\n"
    "}\n"
    "return out;"
)

# The public PUT /workflows schema rejects some newer settings keys with a 400
# "must NOT have additional properties" (binaryMode, timeSavedMode, callerPolicy
# are rejected; availableInMCP and errorWorkflow ARE accepted — verified against
# this instance). Send only accepted keys; the rejected ones reset to defaults.
SETTINGS_ALLOWED = {
    "saveExecutionProgress", "saveManualExecutions", "saveDataErrorExecution",
    "saveDataSuccessExecution", "executionTimeout", "errorWorkflow",
    "timezone", "executionOrder", "availableInMCP",
}


def _req(method: str, path: str, body: dict | None = None) -> dict:
    url = f"{BASE_URL}/api/v1{path}"
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("X-N8N-API-KEY", API_KEY)
    req.add_header("Accept", "application/json")
    if data is not None:
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        sys.exit(f"  HTTP {e.code} on {method} {path}: {e.read().decode()[:400]}")


def _sheets_columns() -> dict:
    """defineBelow mapping for the 16 data columns (channel excluded)."""
    return {
        "mappingMode": "defineBelow",
        "value": {c: f"={{{{ $json.{c} }}}}" for c in COLUMNS},
        "matchingColumns": [],
        "schema": [
            {
                "id": c, "displayName": c, "required": False,
                "defaultMatch": False, "display": True, "type": "string",
                "canBeUsedToMatch": True, "removed": False,
            }
            for c in COLUMNS
        ],
        "attemptToConvertTypes": False,
        "convertFieldsToString": False,
    }


def _build_nodes(sheets_src: dict) -> list[dict]:
    document_id = sheets_src["parameters"]["documentId"]
    return [
        {
            "parameters": {
                "url": FETCH_URL,
                "options": {
                    "response": {"response": {"responseFormat": "json"}},
                    "timeout": 120000,
                },
            },
            "name": "Get video stats",
            "type": "n8n-nodes-base.httpRequest",
            "typeVersion": 4.4,
            "position": [224, 720],
            "onError": "continueErrorOutput",
        },
        {
            "parameters": {"jsCode": SPLIT_JS},
            "name": "Split video rows",
            "type": "n8n-nodes-base.code",
            "typeVersion": 2,
            "position": [448, 720],
        },
        {
            # One item per iteration so the append below resolves sheetName from
            # THAT row's channel. A single googleSheets append resolves its sheet
            # once per batch (it would dump every row into the first row's tab),
            # so per-channel routing requires one row at a time.
            "parameters": {"batchSize": 1, "options": {}},
            "name": "Loop Over Items",
            "type": "n8n-nodes-base.splitInBatches",
            "typeVersion": 3,
            "position": [600, 720],
        },
        {
            "parameters": {
                "authentication": "serviceAccount",
                "operation": "append",
                "documentId": document_id,
                "sheetName": {
                    "__rl": True,
                    "value": "={{ $json.channel }}",
                    "mode": "name",
                },
                "columns": _sheets_columns(),
                "options": {},
            },
            "name": "Append video stats",
            "type": "n8n-nodes-base.googleSheets",
            "typeVersion": 4.7,
            "position": [760, 800],
            "credentials": sheets_src["credentials"],
        },
    ]


def main() -> None:
    if not API_KEY:
        sys.exit("N8N_API_KEY (or N8N_API_TOKEN) env var is required.")
    print(f"{'DRY RUN — ' if DRY_RUN else ''}adding video-stats branch on {BASE_URL}")

    wf = _req("GET", f"/workflows/{WORKFLOW_ID}")
    names = {n["name"] for n in wf["nodes"]}

    for required in (TRIGGER_NODE, SHEETS_NODE, ERROR_NODE):
        if required not in names:
            sys.exit(f"  ABORT — expected node '{required}' not found in workflow")

    sheets_src = next(n for n in wf["nodes"] if n["name"] == SHEETS_NODE)
    if not sheets_src.get("credentials"):
        sys.exit(f"  ABORT — '{SHEETS_NODE}' has no credentials to clone")

    branch = {"Get video stats", "Split video rows", "Loop Over Items", "Append video stats"}
    rebuilding = bool(branch & names)

    # Snapshot non-branch nodes so the safety gate proves we touch nothing else.
    before = {n["name"]: json.dumps(n, sort_keys=True)
              for n in wf["nodes"] if n["name"] not in branch}

    # Converge: drop any prior branch nodes + their connections, then re-add
    # cleanly. Makes the script idempotent AND lets a re-run correct an earlier
    # build (e.g. node order, sheetName).
    wf["nodes"] = [n for n in wf["nodes"] if n["name"] not in branch]
    for bn in branch:
        wf["connections"].pop(bn, None)
    wf["nodes"].extend(_build_nodes(sheets_src))

    # Video branch runs FIRST off the trigger: n8n executes nodes sequentially,
    # so a transient failure in the digest branch (e.g. a Telegram send timeout)
    # would otherwise abort the run before the video branch executes. The video
    # node's own errors route to Format error, so it cannot block the digest either.
    conns = wf["connections"]
    trig_main = conns[TRIGGER_NODE]["main"][0]
    trig_main[:] = [e for e in trig_main if e["node"] != "Get video stats"]
    trig_main.insert(0, {"node": "Get video stats", "type": "main", "index": 0})
    conns["Get video stats"] = {"main": [
        [{"node": "Split video rows", "type": "main", "index": 0}],
        [{"node": ERROR_NODE, "type": "main", "index": 0}],   # error output
    ]}
    conns["Split video rows"] = {"main": [
        [{"node": "Loop Over Items", "type": "main", "index": 0}],
    ]}
    # splitInBatches outputs: index 0 = done (nothing left to do), index 1 = loop.
    conns["Loop Over Items"] = {"main": [
        [],
        [{"node": "Append video stats", "type": "main", "index": 0}],
    ]}
    # Append loops back so the node pulls the next single row each iteration.
    conns["Append video stats"] = {"main": [
        [{"node": "Loop Over Items", "type": "main", "index": 0}],
    ]}

    # Safety gate: every pre-existing non-branch node must be byte-for-byte unchanged.
    for n in wf["nodes"]:
        if n["name"] in branch:
            continue
        if json.dumps(n, sort_keys=True) != before[n["name"]]:
            sys.exit(f"  ABORT — unintended change in existing node '{n['name']}'")

    print(f"  {'rebuilding' if rebuilding else 'adding'} video-stats branch (runs FIRST off the trigger)")
    print("  + node: Get video stats (HTTP GET /analytics/videos)")
    print("  + node: Split video rows (Code: flatten channels[].rows[])")
    print("  + node: Loop Over Items (splitInBatches, batchSize 1 — per-row sheet routing)")
    print("  + node: Append video stats (googleSheets append, sheetName={{channel}})")
    print(f"  + edge: {TRIGGER_NODE} → Get video stats (first) → Split video rows → Loop Over Items")
    print("  + edge: Loop Over Items (loop) → Append video stats → Loop Over Items")
    print("  + edge: Get video stats (error) → Format error")

    if DRY_RUN:
        print("  (dry run — no PUT)")
        return

    settings = {k: v for k, v in wf.get("settings", {}).items() if k in SETTINGS_ALLOWED}
    dropped = sorted(set(wf.get("settings", {})) - set(settings))
    if dropped:
        print(f"    (settings keys reset to default by public API: {', '.join(dropped)})")

    _req("PUT", f"/workflows/{WORKFLOW_ID}", {
        "name": wf["name"],
        "nodes": wf["nodes"],
        "connections": wf["connections"],
        "settings": settings,
    })

    fresh = _req("GET", f"/workflows/{WORKFLOW_ID}")
    fresh_names = {n["name"] for n in fresh["nodes"]}
    added = {"Get video stats", "Split video rows", "Append video stats"} <= fresh_names
    still_active = fresh.get("active", False)
    err_wf = fresh.get("settings", {}).get("errorWorkflow")
    print(f"    -> nodes present: {'OK' if added else 'FAILED'}")
    print(f"    -> active: {still_active} | errorWorkflow: {err_wf}")
    if not still_active:
        _req("POST", f"/workflows/{WORKFLOW_ID}/activate", {})
        print("    -> re-activated workflow")


if __name__ == "__main__":
    main()
