#!/usr/bin/env python3
"""Add the post-upload "Post comment" node to the live channel workflows.

The four channel pipelines ("<Name> — Daily Shorts") are generated by
n8n/generate.py, which now emits a "Post comment" node fanned out from the
upload step (Upload to YouTube → [Post comment, Format success]). This script
applies that same change to the ALREADY-IMPORTED live workflows in n8n so we
don't have to re-import them by hand (which would reset active state).

It patches via the n8n public REST API (GET → edit → PUT → activate),
surgically: it adds ONLY the "Post comment" node and rewires the
"Upload to YouTube" outgoing connection. Every pre-existing node must stay
byte-for-byte unchanged or the script aborts. We deliberately avoid the n8n-mcp
SDK-reconstruction path (it has corrupted expressions before). Idempotent:
re-running drops any prior "Post comment" node and re-adds it cleanly.

The comment node POSTs to /{slug}/comment with the uploaded video_id; the
endpoint is failure-tolerant (always 200) and onError=continueRegularOutput, so
a comment failure (e.g. OAuth token predating the youtube.force-ssl scope) never
breaks the run.

Run:
  N8N_API_KEY=<key> python scripts/add_seed_comment_node.py --dry-run
  N8N_API_KEY=<key> python scripts/add_seed_comment_node.py
(N8N_API_TOKEN is also accepted.)
"""

from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

BASE_URL = os.environ.get("N8N_BASE_URL", "http://100.66.55.82:5678").rstrip("/")
API_KEY = os.environ.get("N8N_API_KEY") or os.environ.get("N8N_API_TOKEN", "")
DRY_RUN = "--dry-run" in sys.argv

API_BASE = "http://host.docker.internal:7860"  # how n8n-in-Docker reaches the API
REPO_ROOT = Path(__file__).resolve().parent.parent
CHANNELS_DIR = REPO_ROOT / "channels"

UPLOAD_NODE = "Upload to YouTube"
COMMENT_NODE = "Post comment"
SUCCESS_NODE = "Format success"

# Same accepted-settings subset as the other patchers (public PUT rejects newer keys).
SETTINGS_ALLOWED = {
    "saveExecutionProgress", "saveManualExecutions", "saveDataErrorExecution",
    "saveDataSuccessExecution", "executionTimeout", "errorWorkflow",
    "timezone", "executionOrder", "availableInMCP",
}


def _req(method: str, path: str, body: dict | None = None) -> dict:
    url = f"{BASE_URL}/api/v1{path}"
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("X-N8N-API-KEY", API_KEY)
    req.add_header("Accept", "application/json")
    if data is not None:
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        sys.exit(f"  HTTP {e.code} on {method} {path}: {e.read().decode()[:400]}")


def _name_to_slug() -> dict[str, str]:
    """{channel display name: slug} from channels/*/channel.json."""
    out: dict[str, str] = {}
    for cfg_path in sorted(CHANNELS_DIR.glob("*/channel.json")):
        cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
        out[cfg["name"]] = cfg["slug"]
    return out


def _comment_node(slug: str) -> dict:
    """Mirror of the node n8n/generate.py emits (id omitted — n8n assigns one)."""
    return {
        "name": COMMENT_NODE,
        "type": "n8n-nodes-base.httpRequest",
        "typeVersion": 4.2,
        "position": [2000, 520],
        "parameters": {
            "method": "POST",
            "url": f"{API_BASE}/{slug}/comment",
            "sendBody": True,
            "contentType": "json",
            "specifyBody": "json",
            "jsonBody": (
                "={\"video_id\": "
                "{{ JSON.stringify($('Upload to YouTube').item.json.video_id) }} }"
            ),
            "options": {"timeout": 30000},
        },
        "onError": "continueRegularOutput",
    }


def patch_workflow(wf_id: str, wf_name: str, slug: str) -> None:
    wf = _req("GET", f"/workflows/{wf_id}")
    names = {n["name"] for n in wf["nodes"]}

    for required in (UPLOAD_NODE, SUCCESS_NODE):
        if required not in names:
            print(f"  [{slug}] SKIP — expected node '{required}' not found")
            return

    already = COMMENT_NODE in names

    # Snapshot every node except the comment node so the gate proves we touch
    # nothing else (connections are allowed to change; nodes are not).
    before = {n["name"]: json.dumps(n, sort_keys=True)
              for n in wf["nodes"] if n["name"] != COMMENT_NODE}

    # Drop any prior comment node + its (absent) connections, then re-add cleanly.
    wf["nodes"] = [n for n in wf["nodes"] if n["name"] != COMMENT_NODE]
    wf["connections"].pop(COMMENT_NODE, None)
    wf["nodes"].append(_comment_node(slug))

    # Rewire: Upload fans out to [Post comment, Format success]. Format success
    # therefore still receives the UPLOAD output (it reads up.url / up.word_id);
    # it is NOT downstream of the comment node. Post comment is terminal.
    wf["connections"][UPLOAD_NODE] = {"main": [[
        {"node": COMMENT_NODE, "type": "main", "index": 0},
        {"node": SUCCESS_NODE, "type": "main", "index": 0},
    ]]}

    # Safety gate: every pre-existing (non-comment) node unchanged byte-for-byte.
    for n in wf["nodes"]:
        if n["name"] == COMMENT_NODE:
            continue
        if json.dumps(n, sort_keys=True) != before.get(n["name"]):
            sys.exit(f"  [{slug}] ABORT — unintended change in node '{n['name']}'")

    verb = "rebuilding" if already else "adding"
    print(f"  [{slug}] {verb} '{COMMENT_NODE}' → POST {API_BASE}/{slug}/comment")
    print(f"  [{slug}] rewire: {UPLOAD_NODE} → [{COMMENT_NODE}, {SUCCESS_NODE}]")

    if DRY_RUN:
        print(f"  [{slug}] (dry run — no PUT)")
        return

    settings = {k: v for k, v in wf.get("settings", {}).items() if k in SETTINGS_ALLOWED}
    _req("PUT", f"/workflows/{wf_id}", {
        "name": wf["name"],
        "nodes": wf["nodes"],
        "connections": wf["connections"],
        "settings": settings,
    })

    fresh = _req("GET", f"/workflows/{wf_id}")
    has_node = COMMENT_NODE in {n["name"] for n in fresh["nodes"]}
    fanout = fresh["connections"].get(UPLOAD_NODE, {}).get("main", [[]])[0]
    fan_names = sorted(e["node"] for e in fanout)
    active = fresh.get("active", False)
    print(f"  [{slug}] -> node present: {'OK' if has_node else 'FAILED'} | "
          f"upload fan-out: {fan_names} | active: {active} | "
          f"errorWorkflow: {fresh.get('settings', {}).get('errorWorkflow')}")
    if not active:
        _req("POST", f"/workflows/{wf_id}/activate", {})
        print(f"  [{slug}] -> re-activated workflow")


def main() -> None:
    if not API_KEY:
        sys.exit("N8N_API_KEY (or N8N_API_TOKEN) env var is required.")
    print(f"{'DRY RUN — ' if DRY_RUN else ''}adding '{COMMENT_NODE}' node on {BASE_URL}\n")

    name_to_slug = _name_to_slug()
    workflows = _req("GET", "/workflows").get("data", [])

    matched = 0
    for wf in workflows:
        wf_name = wf["name"]
        # Channel workflows are named "<Display Name> — Daily Shorts".
        for display_name, slug in name_to_slug.items():
            if wf_name.startswith(display_name) and "Daily Shorts" in wf_name:
                matched += 1
                patch_workflow(wf["id"], wf_name, slug)
                break

    print(f"\nMatched {matched} channel workflow(s).")
    if matched != len(name_to_slug):
        print(f"  WARNING: expected {len(name_to_slug)} (one per channel) — "
              "check workflow names in n8n.")


if __name__ == "__main__":
    main()
